// Parent portal (English / 中文). Mirrors src/app/(parent)/portal of the live app.
import * as S from "../../store.js";
import { esc, chip, section, empty, field, toast, heatmapHtml, mountHeatmap, defaultDetail, coll } from "../../ui.js";
import { today, addDays, diffDays, fmt12, fmtDate, monthGrid, sameMonth, addMonths, weekday, money, DOW } from "../../dates.js";
import { href, go } from "../../router.js";

const T9 = {
  en: { hello: "Hello", next: "Next lesson", inDays: (n) => (n === 0 ? "Today" : n === 1 ? "Tomorrow" : `In ${n} days`), noNext: "No lesson scheduled yet.", change: "Request a different time", pause: "Request a pause", pending: "Change requested · waiting", pkg: "Lesson package", left: (n, t) => `${n} of ${t} lessons left`, paid: "paid", unpaid: "payment pending", renew: (n) => `Only ${n} lesson${n === 1 ? "" : "s"} left in this package — time to renew.`, month: "This month", legend: { done: "Completed", absent: "Absent", up: "Upcoming · tap to request a change", cx: "Cancelled / paused" }, progress: "Progress", taken: "Lessons taken", rate: "Attendance rate", done: "Pieces completed", learning: "In progress", history: "Progress & history →", notes: "Recent lesson notes", allNotes: "All notes", view: "View notes", requests: "My requests", noReq: "No requests yet.", back: "Back", practice: "Practice this week", wentWell: "What went well", workedOn: "What we worked on", minDay: (n) => `${n} min/day`, status: { scheduled: "Scheduled", completed: "Completed", cancelled: "Cancelled", no_show: "Absent", rescheduled: "Moved" }, period: { year: "This year", "12m": "Last 12 months", all: "All time" }, heat: "Last 52 weeks", packages: "Packages", current: "current", pkgPage: "Schedule, attendance & notes", teacherSummary: "Teacher's summary", curTime: "Current time", newDate: "Preferred date", newTime: "Preferred time", reason: "Reason (optional)", send: "Send request", notice: (h) => `Requests need at least ${h} hours' notice. Your teacher will confirm by email.`, waiting: "Waiting for the teacher", approved: "Approved", rejected: "Not possible", countered: "Alternative proposed", withdrawn: "Withdrawn", accept: "Accept", decline: "Decline", withdraw: "Withdraw", teacherProposes: "Teacher proposes", from: "From", to: "To", preview: (n) => `${n} lesson${n === 1 ? "" : "s"} would be skipped and ${n} added after the current schedule:`, previewNone: "No lessons fall in this window. Nothing would change.", pauseNote: "Your teacher reviews the request. You'll get an email (and a text, if enabled) with the new dates once it's approved.", pauseLabel: "Pause", moveLabel: "Move", schedule: "Schedule", attendance: "Attendance", earlier: (n) => `${n} earlier lesson${n === 1 ? "" : "s"} not listed`, movedFrom: "moved from", learningNow: "Learning now", polishing: "Polishing", completedP: "Completed", since: "since", fromNotes: "Pieces and dates come from the teacher's lesson notes.", absences: "Absences", cancelledN: "Cancelled" },
  zh: { hello: "您好", next: "下一节课", inDays: (n) => (n === 0 ? "今天" : n === 1 ? "明天" : `${n} 天后`), noNext: "暂未排课。", change: "申请改时间", pause: "申请暂停", pending: "已申请改期 · 等待老师", pkg: "课包", left: (n, t) => `还剩 ${n} 节（共 ${t} 节）`, paid: "已付款", unpaid: "待付款", renew: (n) => `本期课包仅剩 ${n} 节，请及时续费。`, month: "本月", legend: { done: "已上", absent: "缺席", up: "待上 · 点击申请改期", cx: "取消 / 暂停" }, progress: "学习进度", taken: "已上课节数", rate: "出勤率", done: "已完成曲目", learning: "学习中", history: "进度与记录 →", notes: "最近的课堂笔记", allNotes: "全部笔记", view: "查看笔记", requests: "我的申请", noReq: "暂无申请。", back: "返回", practice: "本周练习", wentWell: "做得好的地方", workedOn: "本节课内容", minDay: (n) => `每天 ${n} 分钟`, status: { scheduled: "已排", completed: "已上", cancelled: "已取消", no_show: "缺席", rescheduled: "已改期" }, period: { year: "今年", "12m": "最近 12 个月", all: "全部" }, heat: "最近 52 周", packages: "课包", current: "进行中", pkgPage: "课程安排、考勤与笔记", teacherSummary: "老师总结", curTime: "当前时间", newDate: "希望的日期", newTime: "希望的时间", reason: "原因（选填）", send: "发送申请", notice: (h) => `改期申请需提前至少 ${h} 小时。老师审核后会发邮件确认。`, waiting: "等待老师审核", approved: "已通过", rejected: "无法安排", countered: "老师提出了其他时间", withdrawn: "已撤回", accept: "接受", decline: "拒绝", withdraw: "撤回", teacherProposes: "老师建议", from: "从", to: "到", preview: (n) => `将跳过 ${n} 节课，并在现有课程表之后补上 ${n} 节：`, previewNone: "该时段内没有课，不会有任何变化。", pauseNote: "老师会审核申请。通过后您会收到邮件（如已开启，还有短信）告知新的日期。", pauseLabel: "暂停", moveLabel: "改期", schedule: "课程安排", attendance: "考勤", earlier: (n) => `另有 ${n} 节更早的课未列出`, movedFrom: "原时间", learningNow: "正在学", polishing: "打磨中", completedP: "已完成", since: "自", fromNotes: "曲目和日期来自老师的课堂笔记。", absences: "缺席", cancelledN: "已取消" },
};
const ctx = () => { const st = S.get(); const fam = S.family(st.portal.familyId); const lang = st.portal.lang; return { st, fam, lang, t: T9[lang], zh: lang === "zh", parent: S.parentsOf(fam.id)[0], students: S.studentsOfFamily(fam.id).filter((s) => s.active) }; };
const fd = (k, zh, style) => (zh ? fmtDate(k, style === "md" ? "zh-md" : "zh") : fmtDate(k, style ?? "short"));
const fdt = (l, zh) => (zh ? `${fmtDate(l.date, "zh")} ${l.time}` : `${fmtDate(l.date)} · ${fmt12(l.time)}`);

function monthView(students, anchor, zh, t) {
  const rows = monthGrid(anchor); const T = today(); const ls = S.get().lessons.filter((l) => students.some((s) => s.id === l.studentId) && l.status !== "rescheduled"); const by = {}; for (const l of ls) (by[l.date] ??= []).push(l);
  const pend = new Set(S.get().requests.filter((r) => r.status === "pending" || r.status === "countered").map((r) => r.lessonId));
  return `<div class="row between mb2"><a class="btn btn-ghost btn-sm" href="${href(`/portal?month=${addMonths(anchor, -1)}`)}">‹</a><b>${zh ? `${anchor.slice(0, 4)}年${Number(anchor.slice(5, 7))}月` : fmtDate(anchor, "month")}</b><a class="btn btn-ghost btn-sm" href="${href(`/portal?month=${addMonths(anchor, 1)}`)}">›</a></div><div class="card" style="overflow:hidden"><div class="cal-dow">${(zh ? ["日", "一", "二", "三", "四", "五", "六"] : DOW).map((d) => `<div>${d}</div>`).join("")}</div>${rows.map((r) => `<div class="cal-row">${r.map((d) => `<div class="cell" style="min-height:3.6rem;cursor:default" ><span class="num ${d === T ? "b" : ""}" style="${d === T ? "background:rgb(var(--accent));color:#fff" : ""}">${sameMonth(d, anchor) ? Number(d.slice(8)) : ""}</span>${(by[d] ?? []).map((l) => { const up = l.status === "scheduled" && d >= T; return `<${up ? `a href="${href(`/portal/lessons/${l.id}/reschedule`)}"` : "span"} class="lchip s-${l.status}" style="cursor:${up ? "pointer" : "default"};text-decoration:${l.status === "cancelled" ? "line-through" : "none"}"><b>${l.time}</b> ${students.length > 1 ? esc(S.studentName(l.studentId).split(" ")[0]) : ""}${pend.has(l.id) ? " ⏳" : ""}</${up ? "a" : "span"}>`; }).join("")}</div>`).join("")}</div>`).join("")}</div><div class="legend"><span><i style="background:rgb(var(--ok))"></i>${t.legend.done}</span><span><i style="background:rgb(var(--warn))"></i>${t.legend.absent}</span><span><i style="background:rgb(var(--brand))"></i>${t.legend.up}</span><span><i style="background:rgb(var(--ink-muted))"></i>${t.legend.cx}</span></div>`;
}

export function home(route) {
  const c = ctx(); const T = today(); const anchor = route.query.month ?? T;
  const cards = c.students.map((s) => { const ls = S.lessonsOf(s.id); const next = ls.filter((l) => l.status === "scheduled" && l.date >= T)[0]; const bal = S.balance(s.id); const pend = next && S.get().requests.find((r) => r.lessonId === next.id && (r.status === "pending" || r.status === "countered")); const taken = ls.filter((l) => S.consumes(l.status)).length; const c2 = ls.filter((l) => l.status === "completed").length; const n2 = ls.filter((l) => l.status === "no_show").length; const rep = c.st.repertoire.filter((r) => r.studentId === s.id);
    return `<div class="card p4 col"><div class="row between"><h2>${esc(s.name)}</h2><a class="small brand" href="${href(`/portal/students/${s.id}`)}">${c.t.history}</a></div>
      <div><div class="muted small">${c.t.next}</div>${next ? `<div class="b" style="font-size:1.4rem">${c.t.inDays(diffDays(T, next.date))}</div><div class="small">${fdt(next, c.zh)}</div>${pend ? `<div class="mt1">${chip("warn", c.t.pending)}</div>` : `<div class="row wrap mt2"><a class="btn btn-outline btn-sm" href="${href(`/portal/lessons/${next.id}/reschedule`)}">${c.t.change}</a><a class="btn btn-ghost btn-sm" href="${href(`/portal/students/${s.id}/pause`)}">${c.t.pause}</a></div>`}` : `<div class="muted">${c.t.noNext}</div>`}</div>
      <div><div class="row between"><span class="muted small">${c.t.pkg}${bal.b ? ` #${bal.b.seq}` : ""}</span>${bal.b ? chip(bal.b.paid ? "ok" : "warn", bal.b.paid ? c.t.paid : c.t.unpaid) : ""}</div>${bal.b ? `<div class="bar mt1"><i style="width:${(bal.b.used / bal.b.total) * 100}%"></i></div><div class="small mt1"><a href="${href(`/portal/sessions/${bal.b.id}`)}">${c.t.left(bal.remaining, bal.total)} · ${c.t.pkgPage} →</a></div>${bal.remaining <= c.st.settings.lowBalanceThreshold ? `<div class="note note-warn mt2">${c.t.renew(bal.remaining)}</div>` : ""}` : ""}</div>
      <div class="grid3"><div class="tile"><div class="v">${taken}</div><div class="k">${c.t.taken}</div></div><div class="tile"><div class="v">${c2 + n2 ? Math.round((c2 / (c2 + n2)) * 100) : 100}%</div><div class="k">${c.t.rate}</div></div><div class="tile"><div class="v">${rep.filter((r) => r.status === "completed").length}<span class="muted" style="font-size:.9rem"> / ${rep.filter((r) => r.status !== "completed").length}</span></div><div class="k">${c.t.done} / ${c.t.learning}</div></div></div></div>`; }).join("");
  const recent = c.st.lessons.filter((l) => c.students.some((s) => s.id === l.studentId) && S.notesOf(l.id)?.status === "final").sort((a, b) => b.date.localeCompare(a.date)).slice(0, 4);
  const html = `<h1>${c.t.hello}, ${esc(c.parent.name.split(" ")[0])}</h1><div class="col3 mt3">${cards}</div>
    ${section(c.t.month, monthView(c.students, anchor, c.zh, c.t))}
    ${section(c.t.notes, recent.length ? `<div class="card list">${recent.map((l) => { const n = S.notesOf(l.id); return `<a class="li" href="${href(`/portal/notes/${l.id}`)}"><div><div class="med">${esc(S.studentName(l.studentId))} · ${fd(l.date, c.zh)}</div><div class="xs muted" style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:20rem">${esc(n.data.message)}</div></div><span class="muted">›</span></a>`; }).join("")}</div>` : empty(c.zh ? "每节课后，课堂笔记会显示在这里。" : "Lesson notes will appear here after each lesson."), `<a class="small brand" href="${href("/portal/requests")}">${c.t.requests} →</a>`)}`;
  return { html };
}

export function student(route) {
  const c = ctx(); const s = S.student(route.params.id); if (!s || s.familyId !== c.fam.id) return { html: empty("Not found") };
  const T = today(); const period = route.query.period ?? "year"; const from = period === "year" ? `${T.slice(0, 4)}-01-01` : period === "12m" ? addDays(T, -365) : "0000";
  const ls = S.lessonsOf(s.id).filter((l) => l.status !== "rescheduled"); const inP = ls.filter((l) => l.date >= from && l.date <= T); const c2 = inP.filter((l) => l.status === "completed").length, n2 = inP.filter((l) => l.status === "no_show").length, x2 = inP.filter((l) => l.status === "cancelled").length;
  const rep = c.st.repertoire.filter((r) => r.studentId === s.id); const group = (st) => rep.filter((r) => r.status === st);
  const sessions = S.sessionsOf(s.id).slice().reverse();
  const html = `<a class="small brand" href="${href("/portal")}">‹ ${c.t.back}</a><h1 class="mt2">${esc(s.name)}</h1>
    ${section(c.t.progress, `<div class="row wrap mb2">${Object.entries(c.t.period).map(([k, l]) => `<a class="chip ${period === k ? "chip-brand" : "chip-muted"}" href="${href(`/portal/students/${s.id}?period=${k}`)}">${l}</a>`).join("")}</div><div class="grid3"><div class="tile"><div class="v">${c2}</div><div class="k">${c.t.taken}</div></div><div class="tile"><div class="v">${c2 + n2 ? Math.round((c2 / (c2 + n2)) * 100) : 100}%</div><div class="k">${c.t.rate}</div></div><div class="tile"><div class="v">${n2}<span class="muted" style="font-size:.9rem"> / ${x2}</span></div><div class="k">${c.t.absences} / ${c.t.cancelledN}</div></div></div><div class="card p3 mt3"><div class="xs muted mb2">${c.t.heat}</div>${heatmapHtml(ls.filter((l) => l.date <= T), { hint: c.zh ? "悬停看日期，点击看当天内容。" : "Hover for the date, click for the day." })}</div>
      <div class="card p3 mt3 col small">${[["in_progress", c.t.learningNow], ["polishing", c.t.polishing], ["completed", c.t.completedP]].map(([k, l]) => `<div><div class="xs muted b">${l}</div>${group(k).map((r) => `<div>${esc(r.title)} <span class="muted">${esc(r.composer ?? "")} · ${c.t.since} ${fd(r.startedOn, c.zh, "md")}${r.completedOn ? ` → ${fd(r.completedOn, c.zh, "md")}` : ""}</span></div>`).join("") || `<div class="muted">—</div>`}</div>`).join("")}<div class="xs muted">${c.t.fromNotes}</div></div>`)}
    ${section(c.t.packages, `<div class="col3">${sessions.map((b) => { const bl = ls.filter((l) => l.sessionId === b.id); const bc = bl.filter((l) => l.status === "completed").length, bn = bl.filter((l) => l.status === "no_show").length; const notes = bl.filter((l) => S.notesOf(l.id)?.status === "final").sort((a, b2) => b2.date.localeCompare(a.date)); return `<div class="card p3 col"><div class="row between"><a class="med" href="${href(`/portal/sessions/${b.id}`)}">#${b.seq} · ${c.t.left(b.total - b.used, b.total)} ${b.status === "active" ? chip("brand", c.t.current) : ""}</a>${chip(b.paid ? "ok" : "warn", b.paid ? c.t.paid : c.t.unpaid)}</div><div class="xs muted">${fd(b.startedAt, c.zh, "md")}${b.completedAt ? ` – ${fd(b.completedAt, c.zh, "md")}` : ""} · ${c.t.attendance}: ${bc} ${c.t.status.completed} · ${bn} ${c.t.status.no_show}</div>${b.parentSummary ? `<div class="note note-info small"><b>${c.t.teacherSummary}:</b> ${esc(b.parentSummary)}</div>` : ""}${notes.length ? `<details><summary class="xs brand" style="cursor:pointer">${c.t.allNotes} (${notes.length})</summary><div class="list mt2">${notes.map((l) => `<a class="li" style="padding-inline:0" href="${href(`/portal/notes/${l.id}`)}"><span class="small">${fd(l.date, c.zh)}</span><span class="xs brand">${c.t.view}</span></a>`).join("")}</div></details>` : ""}</div>`; }).join("")}</div>`)}`;
  return { html, mount(root) { mountHeatmap(root, { lessons: ls.filter((l) => l.date <= T), lang: c.lang, detail: (d, dls) => defaultDetail(d, dls, c.zh, (l) => `/portal/notes/${l.id}`, (l) => (S.notesOf(l.id)?.status === "final" ? `/portal/notes/${l.id}` : `/portal/students/${s.id}`)) }); } };
}

export function pkg(route) {
  const c = ctx(); const b = S.session(route.params.id); if (!b) return { html: empty("Not found") }; const s = S.student(b.studentId);
  const ls = S.get().lessons.filter((l) => l.sessionId === b.id || (l.status === "rescheduled" && S.lesson(l.movedTo)?.sessionId === b.id)).filter((l) => l.status !== "rescheduled").sort((a, b2) => a.date.localeCompare(b2.date));
  const c2 = ls.filter((l) => l.status === "completed").length, n2 = ls.filter((l) => l.status === "no_show").length;
  const html = `<a class="small brand" href="${href(`/portal/students/${s.id}`)}">‹ ${c.t.back}</a><h1 class="mt2">${esc(s.name)} · ${c.t.pkg} #${b.seq}</h1><div class="small muted mt1">${c.t.left(b.total - b.used, b.total)} · ${money(b.priceCents)} · ${b.paid ? c.t.paid : c.t.unpaid}</div>
    ${section(c.t.schedule, `<div class="card list">${ls.map((l) => `<div class="li"><span class="small">${fdt(l, c.zh)}${l.movedFrom ? `<div class="xs muted">${c.t.movedFrom} ${esc(l.movedFrom)}</div>` : ""}</span><span class="row">${S.notesOf(l.id)?.status === "final" ? `<a class="xs brand" href="${href(`/portal/notes/${l.id}`)}">${c.t.view}</a>` : ""}${chip(l.status === "completed" ? "ok" : l.status === "no_show" ? "warn" : l.status === "scheduled" ? "brand" : "muted", c.t.status[l.status])}</span></div>`).join("")}</div>${b.used > c2 + n2 ? `<p class="xs muted mt2">${c.t.earlier(b.used - c2 - n2)}</p>` : ""}`)}
    ${section(c.t.attendance, `<div class="grid3"><div class="tile"><div class="v">${c2}</div><div class="k">${c.t.status.completed}</div></div><div class="tile"><div class="v">${n2}</div><div class="k">${c.t.status.no_show}</div></div><div class="tile"><div class="v">${c2 + n2 ? Math.round((c2 / (c2 + n2)) * 100) : 100}%</div><div class="k">${c.t.rate}</div></div></div>`)}`;
  return { html };
}

export function note(route) {
  const c = ctx(); const l = S.lesson(route.params.id); const n = l && S.notesOf(l.id); if (!n || n.status !== "final") return { html: empty("Not found") }; const s = S.student(l.studentId); const d = n.data;
  const html = `<a class="small brand" href="${href("/portal")}">‹ ${c.t.back}</a><h1 class="mt2">${esc(s.name)}</h1><div class="small muted">${fdt(l, c.zh)}</div>
    <div class="card p4 col3 mt3"><p>${esc(d.message)}</p><div><div class="xs muted b">${c.t.workedOn}</div><div class="row wrap mt1">${d.repertoire.map((r) => chip("brand", `${r.piece}${r.composer ? " · " + r.composer : ""}${r.section ? " · " + r.section : ""}`)).join("")}</div></div><div><div class="xs muted b">${c.t.wentWell}</div><ul class="small" style="list-style:disc;padding-left:20px">${d.wentWell.map((w) => `<li>${esc(w)}</li>`).join("")}</ul></div><div><div class="xs muted b">${c.t.practice} · ${c.t.minDay(d.totalMin)}</div><div class="plan mt1">${d.practice.map((p) => `<div class="it"><span>${esc(p.task)}${p.tip ? `<div class="xs muted">${esc(p.tip)}</div>` : ""}</span><b>${c.t.minDay(p.min)}</b></div>`).join("")}</div></div></div>`;
  return { html };
}

export function reschedule(route) {
  const c = ctx(); const l = S.lesson(route.params.id); if (!l) return { html: empty("Not found") }; const s = S.student(l.studentId); const T = today();
  const existing = S.get().requests.find((r) => r.lessonId === l.id && (r.status === "pending" || r.status === "countered"));
  const tooLate = diffDays(T, l.date) * 24 < c.st.settings.minNoticeHours;
  const html = `<a class="small brand" href="${href("/portal")}">‹ ${c.t.back}</a><h1 class="mt2">${c.t.change}</h1><div class="small muted">${esc(s.name)} · ${c.t.curTime}: ${fdt(l, c.zh)}</div>
    ${existing ? `<div class="note note-warn mt3">${c.t.pending}</div><a class="btn btn-outline mt3" href="${href("/portal/requests")}">${c.t.requests} →</a>` : tooLate ? `<div class="note note-danger mt3">${c.zh ? "已超过在线改期的时限，请直接联系老师。" : "Too late to reschedule online — please contact your teacher directly."}</div>` : `<div class="card p4 col mt3"><div class="grid2">${field(c.t.newDate, `<input class="input" type="date" id="rq-date" value="${addDays(l.date, 1)}" min="${T}">`)}${field(c.t.newTime, `<input class="input" type="time" id="rq-time" value="${l.time}">`)}</div>${field(c.t.reason, `<input class="input" id="rq-reason">`)}<p class="xs muted">${c.t.notice(c.st.settings.minNoticeHours)}</p><button class="btn btn-primary w" id="rq-go">${c.t.send}</button></div>`}`;
  return { html, mount(root) { root.querySelector("#rq-go")?.addEventListener("click", () => { S.createRequest(l.id, root.querySelector("#rq-date").value, root.querySelector("#rq-time").value, root.querySelector("#rq-reason").value); toast(c.zh ? "已发送，等待老师审核" : "Sent · waiting for the teacher"); go("/portal/requests"); }); } };
}

export function pause(route) {
  const c = ctx(); const s = S.student(route.params.id); if (!s) return { html: empty("Not found") }; const T = today(); const open = S.get().pauses.find((p) => p.studentId === s.id && p.status === "pending");
  const html = `<a class="small brand" href="${href("/portal")}">‹ ${c.t.back}</a><h1 class="mt2">${c.t.pause}</h1><div class="small muted">${esc(s.name)}</div><p class="small mt2">${c.zh ? "暂停期间的课会跳过，并在现有课程表之后补上。" : "Lessons in the window are skipped and added back after the current schedule."}</p>
    ${open ? `<div class="note note-warn mt3">${c.t.waiting}: ${fd(open.startsOn, c.zh, "md")} – ${fd(open.endsOn, c.zh, "md")}</div>` : `<div class="card p4 col mt3"><div class="grid2">${field(c.t.from, `<input class="input" type="date" id="pz-from" value="${addDays(T, 7)}" min="${T}">`)}${field(c.t.to, `<input class="input" type="date" id="pz-to" value="${addDays(T, 21)}">`)}</div>${field(c.t.reason, `<input class="input" id="pz-reason">`)}<div id="pz-prev" class="small note note-info"></div><p class="xs muted">${c.t.pauseNote}</p><button class="btn btn-primary w" id="pz-go">${c.t.send}</button></div>`}`;
  return { html, mount(root) { const q = (id) => root.querySelector(id); if (!q("#pz-go")) return; const upd = () => { const ls = S.pausePreview(s.id, q("#pz-from").value, q("#pz-to").value); q("#pz-prev").innerHTML = ls.length ? `${c.t.preview(ls.length)}<div class="mt1">${ls.map((l) => `<span class="chip chip-muted" style="margin:2px">${fd(l.date, c.zh, "md")}</span>`).join("")}</div>` : c.t.previewNone; }; q("#pz-from").addEventListener("input", upd); q("#pz-to").addEventListener("input", upd); upd(); q("#pz-go").addEventListener("click", () => { S.createPause(s.id, q("#pz-from").value, q("#pz-to").value, q("#pz-reason").value); toast(c.zh ? "已发送" : "Sent"); go("/portal/requests"); }); } };
}

export function requests() {
  const c = ctx(); const reqs = S.get().requests.filter((r) => r.familyId === c.fam.id).slice().reverse(); const pz = S.get().pauses.filter((p) => p.familyId === c.fam.id).slice().reverse();
  const lab = (s) => ({ pending: c.t.waiting, approved: c.t.approved, rejected: c.t.rejected, countered: c.t.countered, withdrawn: c.t.withdrawn })[s] ?? s;
  const tone = (s) => ({ pending: "warn", approved: "ok", rejected: "muted", countered: "brand", withdrawn: "muted" })[s];
  const html = `<a class="small brand" href="${href("/portal")}">‹ ${c.t.back}</a><h1 class="mt2">${c.t.requests}</h1>
    ${reqs.length + pz.length ? `<div class="col3 mt3">${reqs.map((r) => { const l = S.lesson(r.lessonId); return `<div class="card p3 col"><div class="row between"><div class="med">${chip("brand", c.t.moveLabel)} ${esc(S.studentName(l.studentId))}</div>${chip(tone(r.status), lab(r.status))}</div><div class="small">${fdt(l, c.zh)} → <b>${c.zh ? `${fmtDate(r.proposedDate, "zh")} ${r.proposedTime}` : `${fmtDate(r.proposedDate)} · ${fmt12(r.proposedTime)}`}</b></div>${r.reason ? `<div class="xs muted">“${esc(r.reason)}”</div>` : ""}${r.teacherNote ? `<div class="small note note-info">${esc(r.teacherNote)}</div>` : ""}${r.status === "countered" ? `<div class="small"><b>${c.t.teacherProposes}:</b> ${c.zh ? `${fmtDate(r.counterDate, "zh")} ${r.counterTime}` : `${fmtDate(r.counterDate)} · ${fmt12(r.counterTime)}`}</div><div class="grid2"><button class="btn btn-primary btn-sm" data-acc="${r.id}">${c.t.accept}</button><button class="btn btn-outline btn-sm" data-wd="${r.id}">${c.t.decline}</button></div>` : r.status === "pending" ? `<button class="btn btn-ghost btn-sm" data-wd="${r.id}">${c.t.withdraw}</button>` : ""}</div>`; }).join("")}${pz.map((p) => `<div class="card p3 col"><div class="row between"><div class="med">${chip("accent", c.t.pauseLabel)} ${esc(S.studentName(p.studentId))}</div>${chip(tone(p.status), lab(p.status))}</div><div class="small">${fd(p.startsOn, c.zh, "md")} – ${fd(p.endsOn, c.zh, "md")}${p.reason ? ` · “${esc(p.reason)}”` : ""}</div>${p.result ? `<div class="small note note-ok">${c.zh ? `跳过 ${p.result.cancelled} 节，补上 ${p.result.created} 节` : `${p.result.cancelled} skipped, ${p.result.created} added`}${p.result.newDates.length ? `: ${p.result.newDates.map((d) => fd(d, c.zh, "md")).join(", ")}` : ""}</div>` : ""}${p.status === "pending" ? `<button class="btn btn-ghost btn-sm" data-wdp="${p.id}">${c.t.withdraw}</button>` : ""}</div>`).join("")}</div>` : empty(c.t.noReq)}`;
  return { html, mount(root) { root.querySelectorAll("[data-acc]").forEach((b) => b.addEventListener("click", () => { S.acceptCounter(b.dataset.acc); toast(c.t.approved); })); root.querySelectorAll("[data-wd]").forEach((b) => b.addEventListener("click", () => S.withdrawRequest(b.dataset.wd))); root.querySelectorAll("[data-wdp]").forEach((b) => b.addEventListener("click", () => S.withdrawPause(b.dataset.wdp))); } };
}
export { coll, weekday };
