import * as S from "../../store.js";
import { LABS, LOCATION_LABEL } from "../../data.js";
import { esc, chip, statusChip, pageHeader, section, coll, empty, field, toast, loc, heatmapHtml, mountHeatmap, openMoveLesson } from "../../ui.js";
import { href as hrefOf } from "../../router.js";
import { today, addDays, fmt12, fmtDate, money, DOW_LONG } from "../../dates.js";
import { href } from "../../router.js";

const LINKS = [["/calendar", "Calendar", "Month / week view; drag to move, click to edit or add"], ["/lessons", "All lessons", "Upcoming, to mark, summaries to send, past"], ["/sessions", "Packages & payments", "Active packages, unpaid"], ["/reports", "Reports", "Attendance, monthly lessons, revenue, CSV export"], ["/notifications", "Sent emails & SMS", "Outbox, failures, retry"], ["/settings", "Studio settings", "Timezone, reminders, contact, experimental features"]];
export function menu() {
  const st = S.get().settings;
  return { html: `${pageHeader("More", { subtitle: esc(st.studioName) })}<div class="grid2 mb3"><button class="btn btn-accent" id="more-move">⇄ Move a lesson</button><a class="btn btn-outline" href="${href("/students")}">📋 Lesson records</a></div><div class="card list">${LINKS.map(([h, l, hint]) => `<a class="li" href="${href(h)}"><div><div class="med">${l}</div><div class="small muted">${hint}</div></div><span class="muted">›</span></a>`).join("")}</div><div class="row between mt6 small muted"><span>${esc(st.teacherEmail)}</span><a class="link" href="${href("/login")}">Sign out</a></div><p class="tc xs muted mt8"><a class="brand" href="#">jillianyang.com</a></p>`, mount(root) { root.querySelector("#more-move").addEventListener("click", () => openMoveLesson(null)); } };
}

export function sessions(route) {
  const f = route.query.filter; const rows = S.get().sessions.filter((b) => (f === "unpaid" ? !b.paid && b.status === "active" : true)).sort((a, b) => (a.status === "active" ? -1 : 1) - (b.status === "active" ? -1 : 1));
  const html = `${pageHeader("Packages & payments", { back: "/more" })}<div class="row mb3"><a class="chip ${f ? "chip-muted" : "chip-brand"}" href="${href("/sessions")}">All</a><a class="chip ${f === "unpaid" ? "chip-brand" : "chip-muted"}" href="${href("/sessions?filter=unpaid")}">Unpaid</a></div>
    <div class="card list">${rows.map((b) => `<div class="li"><div><a class="med" href="${href(`/students/${b.studentId}`)}">${esc(S.studentName(b.studentId))}</a> <span class="muted small">· package #${b.seq}</span><div class="xs muted">${b.used} of ${b.total} used · ${money(b.priceCents)} · ${b.status}${b.paidAt ? ` · paid ${fmtDate(b.paidAt, "mdy")}` : ""}</div></div><button class="btn btn-sm ${b.paid ? "btn-outline" : "btn-primary"}" data-paid="${b.id}">${b.paid ? "Paid ✓" : "Mark paid"}</button></div>`).join("") || `<div class="li muted small">Nothing here.</div>`}</div>`;
  return { html, mount(root) { root.querySelectorAll("[data-paid]").forEach((b) => b.addEventListener("click", () => { S.togglePaid(b.dataset.paid); toast(S.session(b.dataset.paid).paid ? "Marked paid · receipt emailed" : "Marked unpaid"); })); } };
}

export function notifications(route) {
  const f = route.query.status; const rows = S.get().notifications.filter((m) => (f ? m.status === f : true));
  const html = `${pageHeader("Sent emails & SMS", { back: "/more", subtitle: "Every message goes through this outbox. Failed rows can be retried." })}<div class="row wrap mb3">${[["", "All"], ["sent", "Sent"], ["queued", "Queued"], ["failed", "Failed"]].map(([k, l]) => `<a class="chip ${(f ?? "") === k ? "chip-brand" : "chip-muted"}" href="${href(k ? `/notifications?status=${k}` : "/notifications")}">${l}</a>`).join("")}<span class="sp"></span><button class="btn btn-outline btn-sm" id="send-q">Send queued</button></div>
    <div class="card list">${rows.map((m) => `<div class="li"><div><div class="small"><span class="med">${esc(m.subject ?? m.body ?? "")}</span></div><div class="xs muted">${({ sms: "SMS", email: "Email", wechat: "WeChat (copied)" })[m.channel] ?? m.channel} · ${esc(m.recipient)}${m.how === "reviewed" ? " · reviewed" : m.how === "auto" ? " · automatic" : ""} · ${esc(m.event)} · ${esc(m.createdAt)}${m.error ? `<div class="danger">${esc(m.error)}</div>` : ""}</div></div><div class="row">${chip(m.status === "sent" ? "ok" : m.status === "failed" ? "danger" : "muted", m.status)}${m.status === "failed" ? `<button class="btn btn-outline btn-xs" data-retry="${m.id}">Retry</button>` : ""}</div></div>`).join("") || `<div class="li muted small">Nothing here.</div>`}</div>`;
  return { html, mount(root) { root.querySelectorAll("[data-retry]").forEach((b) => b.addEventListener("click", () => { S.retryNotification(b.dataset.retry); toast("Sent"); })); root.querySelector("#send-q").addEventListener("click", () => toast("No queued messages")); } };
}

export function reports() {
  const T = today(); const st = S.get(); const past = st.lessons.filter((l) => l.date <= T && l.status !== "rescheduled");
  const months = {}; for (const l of past) { const k = l.date.slice(0, 7); months[k] ??= { completed: 0, no_show: 0, cancelled: 0, revenue: 0 }; if (months[k][l.status] !== undefined) months[k][l.status]++; if (S.consumes(l.status)) months[k].revenue += l.feeCents; }
  const keys = Object.keys(months).sort().reverse().slice(0, 6);
  const per = st.students.filter((s) => s.active).map((s) => { const ls = past.filter((l) => l.studentId === s.id); const c = ls.filter((l) => l.status === "completed").length, n = ls.filter((l) => l.status === "no_show").length; return { s, c, n, x: ls.filter((l) => l.status === "cancelled").length, rate: c + n ? Math.round((c / (c + n)) * 100) : null }; });
  const html = `${pageHeader("Reports", { back: "/more", action: `<button class="btn btn-outline btn-sm" id="csv">Export CSV</button>` })}
    ${section("By month", `<div class="card tbl-wrap"><table class="tbl"><thead><tr><th>Month</th><th>Completed</th><th>No-show</th><th>Cancelled</th><th>Revenue</th></tr></thead><tbody>${keys.map((k) => `<tr><td>${k}</td><td>${months[k].completed}</td><td>${months[k].no_show}</td><td>${months[k].cancelled}</td><td>${money(months[k].revenue)}</td></tr>`).join("")}</tbody></table></div>`)}
    ${section("Attendance by student", `<div class="card tbl-wrap"><table class="tbl"><thead><tr><th>Student</th><th>Completed</th><th>No-show</th><th>Cancelled</th><th>Rate</th></tr></thead><tbody>${per.map((r) => `<tr><td><a href="${href(`/students/${r.s.id}`)}">${esc(r.s.name)}</a></td><td>${r.c}</td><td>${r.n}</td><td>${r.x}</td><td>${r.rate === null ? "—" : chip(r.rate >= 90 ? "ok" : "warn", `${r.rate}%`)}</td></tr>`).join("")}</tbody></table></div>`)}
    ${section("Last 52 weeks", `<div class="card p3">${heatmapHtml(past)}</div>`)}`;
  return { html, mount(root) { root.querySelector("#csv").addEventListener("click", () => toast("Downloads lessons.csv in the live app")); mountHeatmap(root, { lessons: past, detail: (d, ls) => `<b>${fmtDate(d, "long")}</b>${ls.length ? `<div class="list mt1">${ls.map((l) => `<div class="li" style="padding-inline:0"><span class="small"><a class="med" href="${hrefOf(`/lessons/${l.id}`)}">${esc(S.studentName(l.studentId))}</a> · ${fmt12(l.time)} · ${loc(l.location)}</span>${statusChip(l.status)}</div>`).join("")}</div>` : `<div class="muted small">No lessons this day</div>`}` }); } };
}

export function settings() {
  const st = S.get().settings; const s = S.get();
  const html = `${pageHeader("Studio settings", { back: "/more" })}
    <div class="col3">
      ${coll("Studio & contact", `<div class="col"><div class="grid2">${field("Studio name", `<input class="input" id="st-name" value="${esc(st.studioName)}">`)}${field("Teacher name", `<input class="input" id="st-teacher" value="${esc(st.teacherName)}">`)}</div><div class="grid2">${field("Teacher email", `<input class="input" value="${esc(st.teacherEmail)}">`)}${field("Reply-to for parent emails", `<input class="input" value="${esc(st.replyTo)}">`)}</div><div class="grid3">${field("Timezone", `<input class="input ro" value="${st.timezone}" readonly>`)}${field("Reminder hours ahead", `<input class="input" type="number" value="${st.reminderHours}">`)}${field("Renew reminder when ≤", `<input class="input" type="number" value="${st.lowBalanceThreshold}">`)}</div>${field("Website", `<input class="input" value="${esc(st.websiteUrl)}">`)}<button class="btn btn-primary btn-sm" id="st-save">Save</button></div>`, true)}
      ${coll("Experimental features", `<p class="muted small mb2">Try new screens before they become the default. Switch off any time; nothing is lost.</p><div class="list">${LABS.map((l) => `<div class="li" style="padding-inline:0"><div><div class="med">${esc(l.title)} ${chip("accent", `new · ${l.since}`)}</div><div class="small muted">${esc(l.desc)}</div></div><button class="sw" role="switch" aria-checked="${!!st.labs[l.id]}" aria-label="${esc(l.title)}" data-lab="${l.id}"></button></div>`).join("")}</div>`, true)}
      ${coll("Week plan & scheduler", `<div class="col"><p class="muted small">Which location each weekday is usually at. Exceptions below override a single date. The scheduler warns when a proposed time does not match, and blocks when the commute does not fit.</p><div class="grid3">${DOW_LONG.map((d, i) => field(d.slice(0, 3), `<select class="input" data-dl="${i}">${Object.entries(LOCATION_LABEL).map(([k, v]) => `<option value="${k}" ${st.dayLocations[i] === k ? "selected" : ""}>${v}</option>`).join("")}</select>`)).join("")}</div><div class="grid3">${field("Teaching from", `<input class="input" type="time" id="th-start" value="${st.teachingStart}">`)}${field("to", `<input class="input" type="time" id="th-end" value="${st.teachingEnd}">`)}${field("Buffer between lessons (min)", `<input class="input" type="number" id="th-buf" value="${st.bufferMinutes}">`)}</div>${field("Commute Newmarket ↔ North York (min)", `<input class="input" type="number" id="th-commute" value="${st.commuteMinutes}">`)}<button class="btn btn-outline btn-sm" id="plan-save">Save plan</button>
        <div class="b mt3">Exceptions (one date)</div><div class="list">${s.dayOverrides.map((o) => `<div class="li" style="padding-inline:0"><span class="small">${fmtDate(o.day, "mdy")} → ${loc(o.location)}</span><button class="link xs danger" data-rm-ov="${o.day}">Remove</button></div>`).join("") || `<div class="muted small">None.</div>`}</div><div class="grid3" style="align-items:end"><input class="input" type="date" id="ov-day" value="${addDays(today(), 1)}"><select class="input" id="ov-loc">${Object.entries(LOCATION_LABEL).map(([k, v]) => `<option value="${k}">${v}</option>`).join("")}</select><button class="btn btn-outline btn-sm" id="ov-add">Add exception</button></div>
        <div class="b mt3">Unavailable blocks</div><div class="list">${s.busy.map((b) => `<div class="li" style="padding-inline:0"><span class="small">${fmtDate(b.date, "mdy")} · ${fmt12(b.start)}–${fmt12(b.end)} · ${esc(b.title)}</span><button class="link xs danger" data-rm-busy="${b.id}">Remove</button></div>`).join("") || `<div class="muted small">None.</div>`}</div><div class="grid3" style="align-items:end"><input class="input" type="date" id="bz-date" value="${addDays(today(), 2)}"><div class="row"><input class="input" type="time" id="bz-start" value="13:00"><input class="input" type="time" id="bz-end" value="15:00"></div><input class="input" id="bz-title" placeholder="Orchestra rehearsal"></div><button class="btn btn-outline btn-sm" id="bz-add">Add block</button></div>`)}
      ${coll("Environment", `<p class="muted small mb2">Configuration read from the hosting environment (Vercel → Settings → Environment Variables). Names only; values are never shown.</p><div class="note note-ok mb2">All required settings are present. Database at migration 17 (matches the app).</div><div class="card list small">${["NEXT_PUBLIC_APP_URL", "NEXT_PUBLIC_SUPABASE_URL", "SUPABASE_SERVICE_ROLE_KEY", "ANTHROPIC_API_KEY", "OPENAI_API_KEY", "RESEND_API_KEY", "TWILIO_ACCOUNT_SID"].map((k) => `<div class="li"><code>${k}</code>${chip(k.startsWith("TWILIO") ? "muted" : "ok", k.startsWith("TWILIO") ? "not set (SMS logs only)" : "set")}</div>`).join("")}</div>`)}
    </div>`;
  return { html, mount(root) {
    const q = (id) => root.querySelector(id);
    q("#st-save").addEventListener("click", () => { S.saveSettings({ studioName: q("#st-name").value, teacherName: q("#st-teacher").value }); toast("Saved"); });
    root.querySelectorAll("[data-lab]").forEach((b) => b.addEventListener("click", () => { const on = b.getAttribute("aria-checked") === "true"; S.setLab(b.dataset.lab, !on); toast(`${b.getAttribute("aria-label")} ${on ? "off" : "on"}`); }));
    q("#plan-save").addEventListener("click", () => { const dl = {}; root.querySelectorAll("[data-dl]").forEach((sel) => (dl[sel.dataset.dl] = sel.value)); S.saveSettings({ dayLocations: dl, teachingStart: q("#th-start").value, teachingEnd: q("#th-end").value, bufferMinutes: Number(q("#th-buf").value), commuteMinutes: Number(q("#th-commute").value) }); toast("Plan saved"); });
    root.querySelectorAll("[data-rm-ov]").forEach((b) => b.addEventListener("click", () => S.removeOverride(b.dataset.rmOv)));
    q("#ov-add").addEventListener("click", () => S.addOverride(q("#ov-day").value, q("#ov-loc").value));
    root.querySelectorAll("[data-rm-busy]").forEach((b) => b.addEventListener("click", () => S.removeBusy(b.dataset.rmBusy)));
    q("#bz-add").addEventListener("click", () => S.addBusy(q("#bz-date").value, q("#bz-start").value, q("#bz-end").value, q("#bz-title").value || "Unavailable"));
  } };
}
export { empty };
