import * as S from "../../store.js";
import { esc, chip, pageHeader, section, empty, field, slotHtml, suggestionList, toast, loc, openReview } from "../../ui.js";
import { fmt12, fmtDate, addDays, today } from "../../dates.js";
import { href } from "../../router.js";

export function render() {
  const st = S.get(); const pending = st.requests.filter((r) => r.status === "pending"); const pauses = st.pauses.filter((p) => p.status === "pending"); const past = [...st.requests.filter((r) => r.status !== "pending"), ...st.pauses.filter((p) => p.status !== "pending").map((p) => ({ ...p, pause: true }))].sort((a, b) => (b.createdAt ?? "").localeCompare(a.createdAt ?? "")).slice(0, 10);
  const reqCard = (r) => { const l = S.lesson(r.lessonId); const s = S.student(l.studentId); const fam = S.family(s.familyId); const stale = S.requestStale(r); const check = stale ? { level: "block", reasons: [`This lesson was already ${l.status === "rescheduled" ? "moved" : l.status === "cancelled" ? "cancelled" : "marked"}, so the request can only be declined`] } : S.checkSlot({ date: r.proposedDate, time: r.proposedTime, durationMin: l.durationMin, location: l.location, excludeId: l.id }); const sugg = S.suggestSlots(s.id, r.proposedDate, addDays(r.proposedDate, 10), l.location, 3);
    return `<div class="card p4 col" data-req="${r.id}"><div class="row between"><div><div class="b">${esc(s.name)} <span class="muted small">· ${esc(fam.name)}</span></div><div class="xs muted">asked ${fmtDate(r.createdAt)}</div></div>${chip("brand", "reschedule")}</div>
      <div class="grid2 small"><div><div class="xs muted">Current</div><div>${fmtDate(l.date)} · ${fmt12(l.time)}</div></div><div><div class="xs muted">Proposed</div><div class="b">${fmtDate(r.proposedDate)} · ${fmt12(r.proposedTime)}</div></div></div>
      ${r.reason ? `<div class="small">“${esc(r.reason)}”</div>` : ""}${slotHtml(check)}
      <details><summary class="xs brand" style="cursor:pointer">Other free times near the proposal</summary>${suggestionList(sugg, (g, i) => `<button class="btn btn-outline btn-sm" data-use="${g.date}|${g.time}">Propose</button>`)}</details>
      <input class="input" placeholder="Optional note to the parent" data-note>
      <div class="grid3"><button class="btn btn-primary" data-dec="approve" ${check.level === "block" ? "disabled" : ""}>Approve</button><button class="btn btn-outline" data-dec="counter" ${stale ? "disabled" : ""}>Propose other</button><button class="btn btn-ghost" data-dec="reject">Decline</button></div>
      <div class="grid2 hide" data-counter>${field("Date", `<input class="input" type="date" data-cd value="${r.proposedDate}">`)}${field("Time", `<input class="input" type="time" data-ct value="${r.proposedTime}">`)}<div style="grid-column:span 2" data-cc></div><button class="btn btn-primary" style="grid-column:span 2" data-send-counter>Propose this time</button></div></div>`; };
  const pauseCard = (p) => { const s = S.student(p.studentId); const fam = S.family(s.familyId); const ls = S.pausePreview(s.id, p.startsOn, p.endsOn); return `<div class="card p4 col" data-pause="${p.id}"><div class="row between"><div><div class="b">${esc(s.name)} <span class="muted small">· ${esc(fam.name)}</span></div><div class="xs muted">asked ${fmtDate(p.createdAt)}</div></div>${chip("accent", "pause")}</div><div class="small"><b>${fmtDate(p.startsOn, "mdy")}</b> – <b>${fmtDate(p.endsOn, "mdy")}</b>${p.reason ? ` · “${esc(p.reason)}”` : ""}</div><div class="note note-info">${ls.length} lesson${ls.length === 1 ? "" : "s"} skipped (${ls.map((l) => fmtDate(l.date, "md")).join(", ") || "none"}), ${s.weekday === null ? "no weekly slot so none added" : `${ls.length} added after the current schedule`}.</div><input class="input" placeholder="Optional note to the parent" data-note><div class="grid2"><button class="btn btn-primary" data-pdec="approve">Approve</button><button class="btn btn-ghost" data-pdec="reject">Decline</button></div></div>`; };
  const html = `${pageHeader("Requests", { subtitle: `${pending.length + pauses.length} waiting` })}
    ${pending.length + pauses.length ? `<div class="col3">${pending.map(reqCard).join("")}${pauses.map(pauseCard).join("")}</div>` : empty("Inbox zero", "No pending requests from parents.")}
    ${past.length ? section("Recent decisions", `<div class="card list">${past.map((r) => { const s = S.student(r.pause ? r.studentId : S.lesson(r.lessonId).studentId); return `<div class="li small"><span>${esc(s.name)} · ${r.pause ? `pause ${fmtDate(r.startsOn, "md")}–${fmtDate(r.endsOn, "md")}` : `move to ${fmtDate(r.proposedDate)}`}</span>${chip(r.status === "approved" ? "ok" : r.status === "countered" ? "brand" : "muted", r.status)}</div>`; }).join("")}</div>`) : ""}`;
  return { html, mount(root) {
    root.querySelectorAll("[data-req]").forEach((card) => {
      const id = card.dataset.req; const r = S.get().requests.find((x) => x.id === id); const l = S.lesson(r.lessonId); const note = () => card.querySelector("[data-note]").value;
      const from = { date: l.date, time: l.time }; const fam = S.family(S.student(l.studentId).familyId);
      const decide = (d, cdv, ctv) => {
        const n = note(); const res = S.decideRequest(id, d, n, cdv, ctv); if (res?.error) return toast(res.error, "warn");
        const draft = d === "approve" ? S.draft("approved", { lesson: res.lesson, from, to: { date: r.proposedDate, time: r.proposedTime }, note: n }) : d === "counter" ? S.draft("countered", { lesson: l, from: { date: r.proposedDate, time: r.proposedTime }, to: { date: cdv, time: ctv }, note: n }) : S.draft("declined", { lesson: l, note: n });
        openReview({ title: d === "approve" ? "Approved · tell the parent" : d === "counter" ? "Propose another time" : "Declined · tell the parent", familyId: fam.id, event: d === "approve" ? "reschedule_approved" : d === "counter" ? "reschedule_countered" : "reschedule_rejected", lessonId: res.lesson?.id ?? l.id, sms: d === "approve", draft });
      };
      card.querySelectorAll("[data-dec]").forEach((b) => b.addEventListener("click", () => { const d = b.dataset.dec; if (d === "counter") { card.querySelector("[data-counter]").classList.toggle("hide"); return; } decide(d); }));
      const cd = card.querySelector("[data-cd]"), ct = card.querySelector("[data-ct]"), cc = card.querySelector("[data-cc]"); const upd = () => { const c = S.checkSlot({ date: cd.value, time: ct.value, durationMin: l.durationMin, location: l.location, excludeId: l.id }); cc.innerHTML = slotHtml(c); card.querySelector("[data-send-counter]").disabled = c.level === "block"; }; cd.addEventListener("input", upd); ct.addEventListener("input", upd); upd();
      card.querySelectorAll("[data-use]").forEach((b) => b.addEventListener("click", () => { const [d, t] = b.dataset.use.split("|"); cd.value = d; ct.value = t; upd(); card.querySelector("[data-counter]").classList.remove("hide"); }));
      card.querySelector("[data-send-counter]").addEventListener("click", () => decide("counter", cd.value, ct.value));
    });
    root.querySelectorAll("[data-pause]").forEach((card) => { const id = card.dataset.pause; const p = S.get().pauses.find((x) => x.id === id); card.querySelectorAll("[data-pdec]").forEach((b) => b.addEventListener("click", () => { const note = card.querySelector("[data-note]").value; if (b.dataset.pdec === "approve") { const r = S.applyPause(p.studentId, p.startsOn, p.endsOn, id, note); toast(`Paused: ${r.cancelled} skipped, ${r.created} added · family emailed`); } else { S.rejectPause(id, note); toast("Declined · family emailed"); } })); });
  } };
}
export { loc, today, href };
